### ISSUE TITLE
Is Background_blurred.png useless in the CSS of the full map?

### ISSUE THREAD

**Issue by rybak** [Silverfeelin/AnimalWell-Helper#15]
I've got a question about this line of CSS code:

https://github.com/Silverfeelin/AnimalWell-Helper/blob/6d1cd4627fc9dcc4765331a8b830118792e10a4d/src/styles.scss#L9

it seems that it is useless, because it gets completely negated by this from `.map` when viewing the website:

https://github.com/Silverfeelin/AnimalWell-Helper/blob/6d1cd4627fc9dcc4765331a8b830118792e10a4d/src/app/components/map/map.component.scss#L6

If I disable `.map { background-color: black; }`, then

```css
.leaflet-container {
  background: #ddd;
}
```
from `leaflet.css` comes into play. And only after disabling this layer does `Background_blurred.png` show through.

**Comment by rybak** [comment]
Ahhh, I figured it out. I only look at the full map [https://animal-well.pages.dev/**map**](https://animal-well.pages.dev/map). But `Background_blurred.png` does show through on the Egg-only helper [https://animal-well.pages.dev/**eggs**](https://animal-well.pages.dev/eggs).

Of course, it would have been nice if the full map didn't try to load the unused file.

**Comment by Silverfeelin** [comment]
Since the file is ~1MB I've changed the CSS so the background is not loaded on the map page anymore. Thanks.
92faf4e3acb794c30b6488df3cfa8201d52359e9

Please keep in mind that I'm not very active on this project because I'm mostly working on https://github.com/Silverfeelin/SkyGame-Planner/ whenever I'm motivated.
